version: '3.8'

services:
  api:
    container_name: streaming-now-backend
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: ./backend/build/Dockerfile
    volumes:
      - type: bind
        source: './backend'
        target: '/go/src'
    tty: true