import { default as NextHead } from 'next/head'

export type HeadProps = {
  title?: string
}

export const Head = ({ title = 'Streaming Now?' }: HeadProps) => {
  return (
    <NextHead>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </NextHead>
  )
}
