import { Container } from '@chakra-ui/react'
import Head from 'next/head'
import { ReactNode } from 'react'

import { Footer } from '@/components/Footer'
import { GlobalHeader } from '@/components/GlobalHeader'

export type MainLayoutProps = {
  title?: string
  children: ReactNode
}

export const MainLayout = ({
  title = 'Streaming Now?',
  children
}: MainLayoutProps) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GlobalHeader />
      <Container maxW={{ base: 'container.md', xl: 'container.lg' }}>
        {children}
      </Container>
      <Footer />
    </>
  )
}
