import type { NextPage } from 'next'
import Head from 'next/head'

import { SignInTwitch } from '@/features/twitch-auth'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Streaming Now?</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main>
          <div>Hello world</div>
          <SignInTwitch />
        </main>
        <footer></footer>
      </div>
    </>
  )
}

export default Home
