import type { NextPage } from 'next'
import Head from 'next/head'
import { useQuery } from 'react-query'

import { axios } from '@/lib/axios'

function Test() {
  const { data, isLoading } = useQuery<any>('testQuery', async () => {
    const data = await axios.get('/api/test')
    return data
  })

  if (isLoading) {
    return <p>...Loading</p>
  }

  if (!data) {
    return <p>Error</p>
  }

  return (
    <>
      <div>{data.id}</div>
      <div>{data.title}</div>
    </>
  )
}

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main>
          <div>Hello world</div>
          <Test />
        </main>
        <footer></footer>
      </div>
    </>
  )
}

export default Home
